name: Image Build And Push

on: 
  push:
    branches: 
      - main

jobs:
  gcp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.GAR_HOST }}/${{ secrets.GCP_PROJECT }}/${{ secrets.GAR_REPO }}/srvtwo
          tags: |
            type=sha
          flavor: |
            latest=true
      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.GAR_HOST }}
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}